robot_type: single

data:
  type: teleop
  num_action: 20
  voxel_size: 0.005
  calib_timestamp: single_foar_purplebox

  sample_traj:
    enable: true
    trans_delta: 0.005
    rot_delta: 0.1309
    width_delta: 0.005

  normalization:
    trans_min: [-1.05, -0.70, 0.25]
    trans_max: [1.25, 0.75, 1.80]
    max_gripper_width: 0.1
    img_mean: [0.485, 0.456, 0.406]
    img_std: [0.229, 0.224, 0.225]

  aligner:
    img_size_resnet: [360, 640]
    img_size_dinov2: [252, 448]
    img_size_dinov3: [288, 512]
    img_coord_size_resnet: [12, 20]
    img_coord_size_dinov2: [18, 32]
    img_coord_size_dinov3: [18, 32]

  repeat_dataset: 1
  vis: false
  vis_force_offscreen: true

train:
  workspace:
    min: [-0.85, -0.50, 0.45]
    max: [1.05, 0.55, 1.60]

  augmentation:
    point: true
    aug_trans_min: [-0.2, -0.2, -0.2]
    aug_trans_max: [0.2, 0.2, 0.2]
    aug_rot_min: [-30, -30, -30]
    aug_rot_max: [30, 30, 30]

    color: true
    aug_color_params: [0.4, 0.4, 0.2, 0.1]
    aug_color_prob: 0.2

  lr: 0.0003
  batch_size: 180
  num_workers: 24
  num_steps: 60000
  save_steps: 2500
  num_warmup_steps: 2000
  seed: 233

deploy:
  workspace:
    min: [-0.85, -0.50, 0.45]
    max: [1.05, 0.55, 1.60]

  agent:
    robot_serial: Rizon4-062770
    camera_serial: "104422070117"
    inhand_camera_serial: unknown_inhand
    gripper_port: /dev/ttyUSB0
    gripper_key: width
    enable_init_tcp_pose: false
    gripper_self_test: false

  max_steps: 1
  num_inference_steps: 20
  gripper_threshold: 0.02
  ensemble_mode: new
  seed: 233
  vis: true
  vis_save_dir: /data/haoxiang/logs/single_foar_purplebox_tcp_anchor/eval_debug_vis
  vis_save_png: false
  vis_save_ply: true
  vis_force_offscreen: true

mask_aware:
  enabled: true
  enable_2d_reweight: true
  enable_3d_filter: true
  mask_threshold: 0
  mask_white_is_untrusted: true
  debug_save_mask: true
  debug_save_every: 1
  debug_dir: /data/haoxiang/logs/single_foar_purplebox_tcp_anchor/eval_debug_masks
  debug_print_stats: true
  r_min: 0.001
  interp_eps: 0.000001
  interp_tiny: 0.000001
  empty_cloud_policy: warn_and_skip_filter

  json_mask:
    single_json: /data/haoxiang/data/zihao_foar2/flip_0326_purple_box/calib/result.json
    cam_base_mode: base_to_cam__predef
    use_agent_intrinsics: true
    intrinsics_npy: null
    intrinsic_selector: first
    single_urdf: airexo/airexo/urdf_models/zihao_single_worldbase_y_neg90/left_robot_grav.urdf
    width: 1280
    height: 720
    near_plane: 0.01
    far_plane: 100.0

tcp_anchor:
  enabled: true
  anchor_num_points: 7
  anchor_radius_scale: 0.75
  anchor_color: [0.0, 0.2, 1.0]
  patch_weight_mode: anchor_only
  tcp_patch_radius: 1
  tcp_patch_weight_floor: 1.0
  mask_dilate_kernel: 9

model:
  image_enc: dinov2-base
  cloud_enc_dim: 128
  image_enc_dim: 128
  obs_feature_dim: 512
  hidden_dim: 512
  nheads: 8
  num_attn_layers: 4
  dim_feedforward: 2048
  dropout: 0.1
  interp_fn_mode: custom
  image_enc_finetune: lora
  image_enc_dtype: float32
